#!/usr/bin/env bash

case "$1" in
        server)
            lapis server
            ;;
        shell)
            bash
            ;;
        repl)
            ./repl
            ;;
        *)
            bash
            ;;
esac
