#!/usr/bin/env sh
luap -l set_paths -i -e 'pl = require("pl.import_into")();inspect=require("inspect");Object=require("./classic");Api=require("./Api");split=require("./split");a=Api({});time=require("./time");'
