#!/usr/bin/env sh
luajit -l set_paths -i -e 'inspect=require("inspect");Object=require("./classic");Api=require("./Api");split=require("./split");a=Api({});json=require("./json");time=require("./time");'
